### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by MWLBear** [brotherand2/neteasemusic#1]
闪退

==> Installing…
Selecting previously unselected package com.netease.cloudmusic.
(Reading database ... 6566 files and directories currently installed.)
Preparing to unpack /tmp/_theos_install.deb ...
Unpacking com.netease.cloudmusic (0.0.1-30+debug) ...
Setting up com.netease.cloudmusic (0.0.1-30+debug) ...
install.exec "killall -9 neteasemusic"
No matching processes were found
make: *** [after-install] Error 1

**Comment by MWLBear** [comment]
安装成功会闪退,5s 7.0

**Comment by brotherand2** [comment]
我机子是8,我在8以上都是没问题的,没有7没办法调试,话说,你还在用7机子搞,qq微信支付宝之类还能装上去吗,装不了怎么逆向怎么玩

**Comment by MWLBear** [comment]
-[__NSCFString containsString:]: unrecognized selector sent to instance 0x1700bab80 找到崩溃的原因了啊,7.0没这个方法...有办法把这个系统的法法干吊吗

**Comment by brotherand2** [comment]
.h
#import <Foundation/Foundation.h>

@interface NSString (str)
- (BOOL)containsString:(NSString *)str ;
@end
.m文件
#import "NSString+str.h"

@implementation NSString (str)
-(BOOL)containsString:(NSString *)str
{
      
    return [self rangeOfString:str].location!=NSNotFound;
}
@end
这样就解决了

**Comment by MWLBear** [comment]
加下qq好友,我也是嘉大毕业的哈哈

**Comment by brotherand2** [comment]
什么鬼,我在那里暴露了我的学校

**Comment by brotherand2** [comment]
qq 2387904913

**Comment by MWLBear** [comment]
你的qq啊 大佬..... 547996854@qq.com
